# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Codigo Code Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Codigo Code Test

  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'

end
